# Generated by Django 4.2.4 on 2023-10-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itech', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
