# Generated by Django 4.2.4 on 2023-10-26 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itech', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ur_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop', models.ImageField(default=None, upload_to='media', verbose_name='propic')),
                ('DOB', models.DateField(default=None)),
                ('discription', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(default=None, max_length=100)),
                ('sex', models.CharField(blank=True, choices=[('male', 'female')], max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
