# Generated by Django 4.2.4 on 2023-10-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itech', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ur_details',
            name='prop',
        ),
        migrations.AddField(
            model_name='ur_details',
            name='proPic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ur_details',
            name='DOB',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='ur_details',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ur_details',
            name='sex',
            field=models.CharField(blank=True, choices=[('Female', 'female'), ('Male', 'male')], max_length=7),
        ),
    ]
