# Generated by Django 4.2.4 on 2023-10-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itech', '0004_remove_ur_details_prop_ur_details_propic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ur_details',
            name='coverPhoto',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
    ]
