# Generated by Django 4.2.4 on 2023-11-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itech', '0007_alter_post_pic_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='post'),
        ),
    ]
